/********************************/
--              V1.0            --
/********************************/

-- Ajout du Fichier 0
-- Correction de Fichier 4
-- Correction du fichier 8

-----------------------------------------------------------

/********************************/
--     FICHIERS TRANSVERSES     --
/********************************/

-- Fichier T1

SELECT replace('I^THE' || to_char(SP_CODE_SQ_PK, '000000'), ' ', '')
FROM SP_SPECIALITE;

-- FICHIER T2

SELECT replace('I^PHCGE' || to_char(GSP_GENERIQUE.GSP_PRODUIT_DC_CODE_FK, '00000'), ' ', '') || '^' || SP_SPECIALITE.SP_CODE_SQ_PK
FROM GSP_GENERIQUE, SP_SPECIALITE
WHERE GSP_GENERIQUE.GSP_SP_DC_CODE_FK = SP_SPECIALITE.SP_GSP_CODE_FK;

/********************************/
--         LABORATOIRES         --
/********************************/

-- Fichier numero 0 Config Base (TRAK.DrugDBUpload.CF_OEConfig.txt)

SELECT DEXTR_VER_THER_PK AS VERSION_BASE, DEXTR_DATE_EXTR_PK AS DATE_EXTRACTION
FROM DEXTR_DATE_EXTRACTION;

-- Fichier numero 1 Fabricants (TRAK.DrugDBUpload.PHManufacturer.txt)

SELECT DISTINCT 'I^' || VILLE ||
  '^' || ADRESSE ||
  '^' || CODE_POSTAL ||
  '^' || PAYS ||
  '^PROVINCE' ||
  '^' || CDF_CODE_PK ||
  '^' || LIBELLES_LONG ||
  '^' || TO_CHAR(TEL)
FROM ADR_LABO, CDF_CODIF, SPLAB_SPECIALITE_LABO
WHERE CDF_CODIF.CDF_CODE_PK = SPLAB_SPECIALITE_LABO.SPLAB_CDF_LAB_CODE_FK_PK
AND CDF_CODIF.CDF_NUMERO_PK = '07'
AND ADR_LABO.LIBELLES_LONG = CDF_CODIF.CDF_NOM
AND (ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Titulaire'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Titulaire / Exploitant' 
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Exploitant / Titulaire'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Exploitant/Titulaire'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Titulaire/Exploitant');

-- Fichier numero 2 Distributeurs (TRAK.DrugDBUpload.PHDistributor.txt)

SELECT DISTINCT 'I^' || VILLE ||
  '^' || ADRESSE ||
  '^' || CODE_POSTAL ||
  '^' || PAYS ||
  '^PROVINCE' ||
  '^' || CDF_CODE_PK ||
  '^' || LIBELLES_LONG ||
  '^' || TO_CHAR(TEL)
FROM ADR_LABO, CDF_CODIF, SPLAB_SPECIALITE_LABO
WHERE CDF_CODIF.CDF_CODE_PK = SPLAB_SPECIALITE_LABO.SPLAB_CDF_LAB_CODE_FK_PK
AND CDF_CODIF.CDF_NUMERO_PK = '07'
AND ADR_LABO.LIBELLES_LONG = CDF_CODIF.CDF_NOM
AND (ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Exploitant'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Titulaire / Exploitant' 
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Exploitant / Titulaire'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Exploitant/Titulaire'
  OR ADR_LABO.TITULAIRE_EXPLOITANT LIKE 'Titulaire/Exploitant');
  
/********************************/
--  CONTENU DE LA PRESENTATION  --
/********************************/

-- Fichier numero 3 Contenu Presentation (TRAK.DrugDBUpload.PHCPack.txt)

SELECT DISTINCT replace('I^PHCPATHE' || to_char(PRE.PRE_SP_CODE_FK, '000000'), ' ', '') ||
  '^' || CASE
  WHEN PRE.PRE_NBUNITE IS NULL THEN CONT.PRECONT_NBCONTENANT       -- Si NB_UNITE = NULL alors on renvoie uniquement le NB_CONTENANT
  WHEN (CONT.PRECONT_NBCONTENANT = 1 AND PRE.PRE_NBUNITE IS NOT NULL) THEN PRE.PRE_NBUNITE       -- Si NB CONTENANT = 1 et NB UNITE != NULL alors on renvoie que le NB_UNITE
  ELSE CONT.PRECONT_NBCONTENANT*PRE.PRE_NBUNITE
  END
FROM PRE_PRESENTATION PRE
JOIN PRECONT_PRE_CONTENANT CONT ON (CONT.PRECONT_PRE_CODE_FK_PK = PRE.PRE_CODE_PK);

/********************************/
--    VOIES D'ADMINISTRATION    --
/********************************/

-- Fichier numero 4 Voies d?administration detaillees (TRAK.DrugDBUpload.PHCAdministrationRoute.txt) CHANGER DATE yyyy mm dd

SELECT DISTINCT
  'I^ART' || VO.CDF_CODE_PK ||  -- Code Voie
  '^20140703' ||  -- Date Mise ? Jour
  '^' || VO.CDF_NOM ||  -- Libelle Voie
  '^^' || 'G' -- Type
FROM CDF_CODIF VO
WHERE VO.CDF_NUMERO_PK = '18'
AND VO.CDF_NOM NOT LIKE 'zz%'
AND VO.CDF_NOM NOT LIKE 'ZZ%';

-- Fichier numero 5 Voies d?administration generales (TRAK.DrugDBUpload.OECRoute.txt) CHANGER DATE yyyy mm dd

SELECT DISTINCT 'I^' ||
  RTRIM(LISTAGG('RT' || test1.CDF_CODE_PK || ',') WITHIN GROUP(ORDER BY test1.SPVO_SP_CODE_FK_PK),', ') ||
  '^' || RTRIM(LISTAGG(test1.CDF_NOM || ',') WITHIN GROUP(ORDER BY test1.CDF_CODE_PK),', ') ||
  '^' || '20140305'
FROM (
  SELECT SPVO.SPVO_SP_CODE_FK_PK, SPVO.SPVO_CDF_VO_CODE_FK_PK, CDF_CODE_PK, CDF_NOM
  FROM SPVO_SPECIALITE_VOIE SPVO
  JOIN CDF_CODIF VO ON VO.CDF_CODE_PK = SPVO.SPVO_CDF_VO_CODE_FK_PK
  WHERE VO.CDF_NUMERO_PK = '18'
  AND VO.CDF_NOM NOT LIKE 'zz%'
  AND VO.CDF_NOM NOT LIKE 'ZZ%'
  AND VO.CDF_CODE_PK NOT IN ('61', '62', '83', '84', '85', '99', '100')
  -- AND SPVO_SP_CODE_FK_PK = '14330'
  ) test1
GROUP BY test1.SPVO_SP_CODE_FK_PK;
  
-- Fichier numero 6 Liens voies detaillees Voies generales (TRAK.DrugDBUpload.OECRouteAdmin.txt) GARDER ANCIEN FICHIER

/*SELECT DISTINCT 'I^PHCrt' || VO.CDF_CODE_PK || '^ROUTErt' || VOIE_GEN.CODE_VG
FROM (
  SELECT VG.SPVO_CODE AS CODE_SP,
    RTRIM(LISTAGG('rt' || VG.CDF || ',') WITHIN GROUP(ORDER BY VG.SPVO_CODE),', ') AS CODE_VG
  FROM 
    (
    SELECT SPVO.SPVO_SP_CODE_FK_PK AS SPVO_CODE, SPVO.SPVO_CDF_VO_CODE_FK_PK AS vGen, CDF_CODE_PK AS CDF, CDF_NOM
    FROM SPVO_SPECIALITE_VOIE SPVO
    JOIN CDF_CODIF VO ON VO.CDF_CODE_PK = SPVO.SPVO_CDF_VO_CODE_FK_PK
    WHERE VO.CDF_NUMERO_PK = '18'
    AND VO.CDF_NOM NOT LIKE 'zz%'
    AND VO.CDF_NOM NOT LIKE 'ZZ%'
    AND VO.CDF_CODE_PK NOT IN ('61', '62', '83', '84', '85', '99', '100')
    --AND SPVO_SP_CODE_FK_PK = '14330'
    ) VG
  GROUP BY VG.SPVO_CODE
  ) VOIE_GEN
JOIN SPVO_SPECIALITE_VOIE SPVO ON SPVO.SPVO_SP_CODE_FK_PK = VOIE_GEN.CODE_SP
JOIN CDF_CODIF VO ON VO.CDF_CODE_PK = SPVO.SPVO_CDF_VO_CODE_FK_PK
WHERE VO.CDF_NUMERO_PK = '18'
AND VO.CDF_NOM NOT LIKE 'zz%'
AND VO.CDF_NOM NOT LIKE 'ZZ%'
AND VO.CDF_CODE_PK NOT IN ('61', '62', '83', '84', '85', '99', '100')
--AND SPVO_SP_CODE_FK_PK = '14330'
--ORDER BY VOIE_GEN.CODE_VG
;*/

/********************************/
--     LISTE PRESCRIPTION      --
/********************************/

-- Fichier numero 7 Liste Prescription (TRAK.DrugDBUpload.PHCPoison.txt)

SELECT
  'I^PHCPO' || replace(TO_CHAR(CDF.CDF_CODE_PK, '00'), ' ','') ||
  '^' || CDF.CDF_NOM
FROM CDF_CODIF CDF
WHERE CDF_NUMERO_PK = '08'
AND CDF.CDF_NOM NOT LIKE 'LISTE EN COURS';
  
/********************************/
--        INTERACTIONS         --
/********************************/

-- Fichier numero 8 Niveaux d?interactions (TRAK.DrugDBUpload.PHCDrugInteractSeverity.txt)

SELECT DISTINCT replace('I^DRGINTS' || to_char(FIT.FIT_CODE_SQ_PK, '000000'), ' ', '') || '^^^^' || CDF_IN.CDF_NOM
FROM FIT_FICHEINTERAC FIT
JOIN FITNA_INTERACTION_NATURE FITNA ON FITNA.FITNA_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN CDF_CODIF CDF_IN ON (CDF_IN.CDF_CODE_PK = FITNA.FITNA_CDF_NAIT_CODE_FK_PK
  AND CDF_IN.CDF_NUMERO_PK = 'IN')
;

---- Fichier de la version pr?c?dente
/*SELECT DISTINCT replace('I^DRGINTS' || to_char(FIT.FIT_CODE_SQ_PK, '000000'), ' ', '') ||
  '^20140318^' || NOM1.CDF_NOM || ' ET ' || NOM2.CDF_NOM || '^' || CDF_IN.CDF_NOM
FROM FIT_FICHEINTERAC FIT
JOIN IT1CC_TERM1COMCLASSE IT1 ON IT1.IT1CC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN CDF_CODIF NOM1 ON (NOM1.CDF_CODE_PK = IT1.IT1CC_CDF_CC_CODE_FK_PK
  AND NOM1.CDF_NUMERO_PK = 'IC')
JOIN IT2CC_TERM2COMCLASSE IT2 ON (IT2.IT2CC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
  AND IT2.IT2CC_FIT_CODE_FK_PK = IT1.IT1CC_FIT_CODE_FK_PK)
JOIN CDF_CODIF NOM2 ON (NOM2.CDF_CODE_PK = IT2.IT2CC_CDF_CC_CODE_FK_PK
  AND NOM2.CDF_NUMERO_PK = 'IC')
JOIN FITNA_INTERACTION_NATURE FITNA ON FITNA.FITNA_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN CDF_CODIF CDF_IN ON (CDF_IN.CDF_CODE_PK = FITNA.FITNA_CDF_NAIT_CODE_FK_PK
  AND CDF_IN.CDF_NUMERO_PK = 'IN')
-- Pour le cas ORLISTAT
--WHERE NOM2.CDF_NOM LIKE 'ORLISTAT'
;*/

/********************************/
--          GROSSESSE          --
/********************************/

-- Fichier numero 9 Grossesse (TRAK.DrugDBUpload.PACPregnancyCategory.txt)

SELECT DISTINCT replace('I^PREGCAT' || to_char(SUBSTR(CDF_CODIF.CDF_CODE_PK,2,3), '00000'), ' ', '') || -- Code Theso
  '^' || CDF_CODIF.CDF_NOM || -- Libelle
  '^'-- || replace(replace(to_char(CDF_CODIF.CDF_DATEMJ,'DD-Mon-YYYY'), '.', ''), ' ','') -- Date MJ
FROM CDF_CODIF
WHERE CDF_CODIF.CDF_NUMERO_PK = 'GR'
AND CDF_CODIF.CDF_CODE_PK LIKE 'R%'
AND CDF_CODIF.CDF_CODE_PK NOT IN ('R10', 'R13', 'R6', 'R7', 'R25', 'R20', 'R15', 'R11', 'R14', 'R9', 'R2','R', 'R26')
ORDER BY 1;

/********************************/
--       HYPERSENSIBILITES      --
/********************************/

-- Fichier numero 10 Familles d?Hypersensibilites (TRAK.DrugDBUpload.PHCAllergyGroup.txt)

SELECT replace('I^ALGR' || to_char(ID, '00000'), ' ', '') || '^' || NOM
FROM FAMILLE;

-- Fichier numero 11 Hypersensibilites croisees (TRAK.DrugDBUpload.PHCAllergyXSens.txt)

SELECT replace('I^ALXS' || to_char(MIN(ID), '00000'), ' ', '') || '^' || HYPER
FROM CROISEE
GROUP BY HYPER
;
SELECT * FROM CROISEE;

/********************************/
--    CLASSE PHARMACOLOGIQUE    --
/********************************/

-- Fichier numero 12 ATC Niveau 2 (TRAK.DrugDBUpload.PHCCat.txt)

SELECT 'I^PHCC' || CATC_CATC_CODE_FK || '^' || CATC_NOMF
FROM CATC_CLASSEATC
WHERE LENGTH(CATC_CATC_CODE_FK) = 3;

-- Fichier numero 13 ATC Niveau 3 (TRAK.DrugDBUpload.PHCMinorSubCat.txt)

SELECT 'I^PHCC' || ATC1.CATC_CATC_CODE_FK || '^' || ATC1.CATC_NOMF
  || '^PHCSC' || ATC2.CATC_CATC_CODE_FK || '^' || ATC2.CATC_NOMF
FROM CATC_CLASSEATC ATC1, CATC_CLASSEATC ATC2
WHERE SUBSTR(ATC2.CATC_CATC_CODE_FK,1,3) = ATC1.CATC_CATC_CODE_FK
AND LENGTH(ATC1.CATC_CATC_CODE_FK) = 3
AND LENGTH(ATC2.CATC_CATC_CODE_FK) = 4;

-- Correction du fichier :

SELECT DISTINCT 'I^MIN' || ATC.CATC_CODE_PK || '^' || ATC3.CATC_CODE_PK || '^' || ATC0.CATC_NOMF || ' - ' || ATC3.CATC_NOMF || ' - ' || ATC2.CATC_NOMF || ' - ' || ATC.CATC_NOMF || '^' || ATC2.CATC_CODE_PK
FROM CATC_CLASSEATC ATC0, CATC_CLASSEATC ATC, CATC_CLASSEATC ATC2, CATC_CLASSEATC ATC3
WHERE ATC0.CATC_CATC_CODE_FK = ATC.CATC_CODE_PK
AND ATC.CATC_CATC_CODE_FK = ATC2.CATC_CODE_PK
AND ATC2.CATC_CATC_CODE_FK = ATC3.CATC_CODE_PK
AND LENGTH(ATC.CATC_CODE_PK) = 5;
--AND ATC3.CATC_CODE_PK = 'D01';

-- Fichier numero 14 ATC Niveau 4 (TRAK.DrugDBUpload.PHCSubCat.txt)

SELECT 'I^PHCC' || ATC1.CATC_CATC_CODE_FK || '^' || ATC1.CATC_NOMF
  || '^PHCSC' || ATC2.CATC_CATC_CODE_FK || '^' || ATC2.CATC_NOMF
  || '^MIN' || ATC3.CATC_CATC_CODE_FK || '^' || ATC3.CATC_NOMF
FROM CATC_CLASSEATC ATC1, CATC_CLASSEATC ATC2, CATC_CLASSEATC ATC3
WHERE SUBSTR(ATC2.CATC_CATC_CODE_FK,1,3) = ATC1.CATC_CATC_CODE_FK
AND SUBSTR(ATC3.CATC_CATC_CODE_FK,1,4) = ATC2.CATC_CATC_CODE_FK
AND LENGTH(ATC1.CATC_CATC_CODE_FK) = 3
AND LENGTH(ATC2.CATC_CATC_CODE_FK) = 4
AND LENGTH(ATC3.CATC_CATC_CODE_FK) = 5;

-- Correction du fichier :

SELECT DISTINCT 'I^PHCSC' || ATC.CATC_CATC_CODE_FK || '^' || ATC2.CATC_NOMF || ' - ' || ATC.CATC_NOMF || '^PHCC' || ATC.CATC_CODE_PK
FROM CATC_CLASSEATC ATC, CATC_CLASSEATC ATC2
WHERE ATC.CATC_CATC_CODE_FK = ATC2.CATC_CODE_PK
AND LENGTH(ATC.CATC_CODE_PK) = 4;

/********************************/
--          SUBSTANCES          --
/********************************/

-- Fichier numero 15 Substances (TRAK.DrugDBUpload.PHCIngredient.txt)

SELECT replace('I^IN' || to_char(GSAC_CODE_SQ_PK, '00000'), ' ', '') || '^' || replace(GSAC_NOM, ' ','') 
FROM GSAC_PERE_SUBACT GS
WHERE GS.GSAC_NOM NOT LIKE 'zz%';

/********************************/
--            FORMES            --
/********************************/

-- Fichier numero 16 Formes (TRAK.DrugDBUpload.PHCForm.txt)

SELECT replace('I^PHCFfr' || to_char(FO.CDF_CODE_PK, '00000'), ' ', '') || '^' || FO.CDF_NOM
FROM CDF_CODIF FO
WHERE FO.CDF_NUMERO_PK = '06'
AND FO.CDF_NOM NOT LIKE 'zz%zz'
AND FO.CDF_NOM NOT LIKE 'NON RENSEIGNEE';

/********************************/
--     CLASSE D?EQUIVALENCE     --
/********************************/

-- Fichier numero 17 Classe d??quivalence (TRAK.DrugDBUpload.PHCDuplicateTherClass.txt)

SELECT 'I^DTC' || CATC_CATC_CODE_FK || '^' || CATC_NOMF || '^0'
FROM CATC_CLASSEATC
WHERE LENGTH(CATC_CATC_CODE_FK) = 5
AND CATC_CATC_CODE_FK = 'N05CD';

/********************************/
--        ADMINISTRATION        --
/********************************/

-- Fichier numero 18 Administration (TRAK.DrugDBUpload.PHCInstruc.txt)

SELECT 'I^PHCIN' ||
  CASE
  WHEN LENGTH(RC.CDF_CODE_PK) = '1' THEN ('0000' || RC.CDF_CODE_PK)
  WHEN LENGTH(RC.CDF_CODE_PK) = '2' THEN ('000' || RC.CDF_CODE_PK)
  WHEN LENGTH(RC.CDF_CODE_PK) = '3' THEN ('00' || RC.CDF_CODE_PK)
  WHEN LENGTH(RC.CDF_CODE_PK) = '4' THEN ('0' || RC.CDF_CODE_PK)
  ELSE 'RC.CDF_CODE_PK'
  END || '^' || RC.CDF_NOM
FROM CDF_CODIF RC
WHERE RC.CDF_NUMERO_PK = 'RC'
AND RC.CDF_NOM NOT LIKE 'zz%zz'
AND RC.CDF_NOM NOT LIKE 'ZZ%ZZ'
AND RC.CDF_NOM NOT LIKE 'ET'
AND RC.CDF_NOM NOT LIKE 'OU';

/********************************/
--           DOSAGES           --
/********************************/

-- Fichier numero 19 Dosages (TRAK.DrugDBUpload.PHCStrength.txt)

SELECT DISTINCT 'I^' || CONVERT(COSAC_COMPO_SUBACT.COSAC_DOSAGE, 'US7ASCII', 'UTF8') || UPPER(COSAC_COMPO_SUBACT.COSAC_UNITEDOSAGE) || '^' || CONVERT(COSAC_COMPO_SUBACT.COSAC_DOSAGE, 'US7ASCII', 'UTF8') || UPPER(COSAC_COMPO_SUBACT.COSAC_UNITEDOSAGE)
FROM COSAC_COMPO_SUBACT, COMPO_COMPOSITION
WHERE COSAC_COMPO_SUBACT.COSAC_SP_CODE_FK_PK = COMPO_COMPOSITION.COMPO_SP_CODE_FK_PK
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSIGNE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEINGE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNEE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEINGNEE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NR';

SELECT DISTINCT COSAC_COMPO_SUBACT.COSAC_DOSAGE, COSAC_COMPO_SUBACT.COSAC_UNITEDOSAGE FROM COSAC_COMPO_SUBACT;

/********************************/
--       DOSE TOTALE UCD       --
/********************************/

-- Fichier numero 20 Dose Totale UCD (TRAK.DrugDBUpload.CTUOM.txt)

-- Requ?te corrig?e

SELECT DISTINCT 'I^' || COSAC_COMPO_SUBACT.COSAC_UNITEDOSAGE || '^' || COSAC_COMPO_SUBACT.COSAC_UNITEDOSAGE
FROM COSAC_COMPO_SUBACT
WHERE COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSIGNE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEINGE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNEE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NON RENSEINGNEE'
AND COSAC_COMPO_SUBACT.COSAC_DOSAGE NOT LIKE 'NR';

--Ancienne

SELECT DISTINCT 
  'I^CTUOM' || replace(to_char(CDF_FO.CDF_CODE_PK, '00000'), ' ', '') ||
  '^' || CDF_FO.CDF_NOM ||
  '^' || COMPO.COSAC_DOSAGE ||
  '^' || COMPO.COSAC_UNITEDOSAGE ||
  '^' || SAC.SAC_NOM
FROM SP_SPECIALITE SP
JOIN SPFO_SPECIALITE_FORME FORME on (FORME.SPFO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
  AND (SPFO_NUMORD = 1 OR SPFO_NUMSEQ_PK = 1))
JOIN CDF_CODIF CDF_FO ON (CDF_FO.CDF_CODE_PK = FORME.SPFO_CDF_FO_CODE_FK_PK
  AND CDF_FO.CDF_NUMERO_PK = '06'
  AND CDF_FO.CDF_NOM NOT LIKE 'zz%zz'
  AND CDF_FO.CDF_NOM NOT LIKE 'NON RENSEIGNEE')
JOIN COSAC_COMPO_SUBACT COMPO ON COMPO.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN SAC_SUBACTIVE SAC ON SAC.SAC_CODE_SQ_PK = COMPO.COSAC_SAC_CODE_FK_PK;

/********************************/
--        INTERACTIONS         --
/********************************/

-- Fichier numero 21 Description interactions (TRAK.DrugDBUpload.PHCMonograph.txt)

-- A modifier Oct 2014: Utiliser table FIT_FICHEINTERAC : I^FIT_CODE_SQ_PK^FIT_TEXTE
SELECT * FROM FIT_FICHEINTERAC;
--
SELECT 'I^MGR' || replace(to_char(CDF_CODE_PK, '00000'), ' ', '') || '^' || CDF_NOM
FROM CDF_CODIF
WHERE CDF_NUMERO_PK = 'IY'
AND CDF_NOM NOT LIKE 'zz%'
AND CDF_NOM NOT LIKE 'NON RENSEIGNE';

/********************************/
--    PRODUITS DC (GENERICS)    --
/********************************/

-- Fichier numero 22 Produits DC (TRAK.DrugDBUpload.PHCGeneric.txt)

SELECT 'I^PHCGE' || ID ||
  '^' || LABEL ||
  '^' || replace(replace(to_char(CREATED_AT,'YYYYMMDD'), '.', ''), ' ','')
FROM PRODUIT_DC;

/********************************/
--LIENS PRODUITS DC - SUBSTANCES--
/********************************/

--Fichier numero 23 Produits DC - Substances (TRAK.DrugDBUpload.PHCGenericIngr.txt)

SELECT * FROM PRODUIT_DC WHERE ID ='1023';
SELECT * FROM GSP_GENERIQUE WHERE GSP_PRODUIT_DC_CODE_FK = '1023';
SELECT * FROM SP_SPECIALITE WHERE SP_GSP_CODE_FK = '2478';
SELECT * FROM COSAC_COMPO_SUBACT WHERE COSAC_SP_CODE_FK_PK = '6019';

SELECT DISTINCT replace('I^INGR' || to_char(COMPO.COSAC_SAC_CODE_FK_PK, '00000'), ' ', '') || '^' || replace('PHCGE' || to_char(DC.ID, '00000'), ' ', '')
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_SP_DC_CODE_FK
  AND SP.SP_CDF_SLAB_CODE_FK = '2'
JOIN COSAC_COMPO_SUBACT COMPO ON COMPO.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
--WHERE DC.ID = '1023'
;

/***************************************/
--LIENS PRODUITS DC - HYPERSENSIBILITES--
/***************************************/

-- Fichier numero 24 Produits DC - Hypersensibilit?s (TRAK.DrugDBUpload.PHCGenericAlrgGroup.txt)

SELECT DISTINCT replace('I^ALGR' || to_char(FAM.ID, '00000'), ' ', '') || '^' || replace('I^PHCGE' || to_char(DC.ID, '00000'), ' ', '')
FROM PRODUIT_DC DC, COSAC_COMPO_SUBACT COMPO, GSP_GENERIQUE GSP, SP_SPECIALITE SP, FAMILLE_SAC FAM_SAC, FAMILLE FAM
WHERE DC.ID = GSP.GSP_PRODUIT_DC_CODE_FK
AND GSP.GSP_GSP_CODE_FK = SP.SP_GSP_CODE_FK
AND SP.SP_CODE_SQ_PK = COMPO.COSAC_SP_CODE_FK_PK
AND COMPO.COSAC_SAC_CODE_FK_PK = FAM_SAC.SAC_CODE
AND FAM_SAC.FAMILLE_ID = FAM.ID;

-- Fichier numero 25 Produits DC ? Hypersensibilit?s crois?es (TRAK.DrugDBUpload.PHCGenericAlrgXSens.txt)

SELECT DISTINCT replace('I^ALXS' || to_char(CR.ID, '00000'), ' ', '') || '^' || replace('PHCGE' || to_char(DC.ID, '00000'), ' ', '')
FROM PRODUIT_DC DC, COSAC_COMPO_SUBACT COMPO, GSP_GENERIQUE GSP, SP_SPECIALITE SP, CROISEE CR
WHERE DC.ID = GSP.GSP_PRODUIT_DC_CODE_FK
AND GSP.GSP_GSP_CODE_FK = SP.SP_GSP_CODE_FK
AND SP.SP_CODE_SQ_PK = COMPO.COSAC_SP_CODE_FK_PK
AND (COMPO.COSAC_SAC_CODE_FK_PK = CR.ID1
OR COMPO.COSAC_SAC_CODE_FK_PK = CR.ID2)
AND SACSAU1 NOT LIKE 'Sau' AND SACSAU2 NOT LIKE 'Sau';

SELECT * FROM CROISEE WHERE ID='82';

-- Fichier numero 26 Produits DC ? Forme, Voie, Dosage, Classe (TRAK.DrugDBUpload.PHCGenericRtForms.txt)

SELECT DISTINCT 'I^PHCGE' || DC.ID ||
  '^PHCFfr' || SPFO.SPFO_CDF_FO_CODE_FK_PK ||
  '^PHCrt' || SPVO.SPVO_CDF_VO_CODE_FK_PK ||
  '^' || COSAC.COSAC_DOSAGE || COSAC.COSAC_UNITEDOSAGE ||
  'I^PHCC' || CATC1.CATC_CATC_CODE_FK || '^' || CATC1.CATC_NOMF
  || '^' || CATC2.CATC_CATC_CODE_FK || '^' || CATC2.CATC_NOMF
  || '^' || CATC3.CATC_CATC_CODE_FK || '^' || CATC3.CATC_NOMF AS Requete26
FROM PRODUIT_DC DC
-- Jointure du g?n?rique avec la Sp?
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_GSP_CODE_FK
-- Jointure de la sp? avec la forme
JOIN SPFO_SPECIALITE_FORME SPFO ON SPFO.SPFO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
-- Jointure de la sp? avec la voie
JOIN SPVO_SPECIALITE_VOIE SPVO ON SPVO.SPVO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
-- Jointure de la sp? avec le dosage
JOIN COSAC_COMPO_SUBACT COSAC ON COSAC.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NON RENSIGNE'
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNE'
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NON RENSEINGE'
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNEE'
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NON RENSEINGNEE'
  AND COSAC.COSAC_DOSAGE NOT LIKE 'NR'
-- Jointure de la sp? avec la classe ATC
JOIN CATC_CLASSEATC CATC1 ON (CATC1.CATC_CODE_PK = SP.SP_CATC_CODE_FK
  AND LENGTH(CATC1.CATC_CATC_CODE_FK) = 3)
JOIN CATC_CLASSEATC CATC2 ON (SUBSTR(CATC2.CATC_CATC_CODE_FK,1,3) = CATC1.CATC_CATC_CODE_FK
  AND LENGTH(CATC2.CATC_CATC_CODE_FK) = 4)
JOIN CATC_CLASSEATC CATC3 ON (SUBSTR(CATC3.CATC_CATC_CODE_FK,1,4) = CATC2.CATC_CATC_CODE_FK
  AND LENGTH(CATC3.CATC_CATC_CODE_FK) = 5)
;

-- Fichier numero 27 Produits DC ? Classes d??quivalence (TRAK.DrugDBUpload.PHCGenericRtFormsDTherCl.txt)

SELECT DISTINCT replace('I^PHCGE' || to_char(DC.ID, '00000'), ' ', '') || '^DTC' || CATC.CATC_CODE_PK
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_GSP_CODE_FK
JOIN CATC_CLASSEATC CATC ON CATC.CATC_CODE_PK = SP.SP_CATC_CODE_FK
;

-- Fichier numero 28 Produits DC ? Interactions (TRAK.DrugDBUpload.PHCGenericRtFormsInter.txt)

SELECT DISTINCT replace('I^GEN' || to_char(DC1.ID, '00000'), ' ', '') || 
  '^rt' || CDFVO1.CDF_CODE_PK ||
  '^fr' || CDFFO1.CDF_CODE_PK || '^' ||
  CASE
    WHEN FITVD1.FITVD1_DOSE1 IS NULL THEN ''
    WHEN CDFDO1.CDF_NOM IS NULL THEN ''
    ELSE FITVD1.FITVD1_DOSE1 || CDFDO1.CDF_NOM
  END || '^' ||
  replace('GEN' || to_char(DC2.ID, '00000'), ' ', '') || 
  '^rt' || CDFVO2.CDF_CODE_PK ||
  '^fr' || CDFFO2.CDF_CODE_PK || '^' ||
  CASE 
    WHEN FITVD2.FITVD2_DOSE2 IS NULL THEN ''
    WHEN CDFDO2.CDF_NOM IS NULL THEN ''
    ELSE FITVD2.FITVD2_DOSE2 || CDFDO2.CDF_NOM
  END ||
  '^' || IT1SP.IT1SP_FIT_CODE_FK_PK ||
  '^' || FITNA.FITNA_CDF_NAIT_CODE_FK_PK
FROM FIT_FICHEINTERAC FIT
JOIN IT1SP_TERME1SPECIALITE IT1SP ON IT1SP.IT1SP_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN SP_SPECIALITE SP1 ON SP1.SP_CODE_SQ_PK = IT1SP.IT1SP_SP_CODE_FK_PK
JOIN GSP_GENERIQUE GSP1 ON GSP1.GSP_GSP_CODE_FK = SP1.SP_GSP_CODE_FK
JOIN PRODUIT_DC DC1 ON DC1.ID = GSP1.GSP_PRODUIT_DC_CODE_FK

-- Jointure entre la voie de sp?cialit? et la sac
JOIN SPVO_SPECIALITE_VOIE SPVO1 ON SPVO1.SPVO_SP_CODE_FK_PK = SP1.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFVO1 ON (CDFVO1.CDF_CODE_PK = SPVO1.SPVO_CDF_VO_CODE_FK_PK
  AND CDFVO1.CDF_NUMERO_PK = '18'
  AND CDFVO1.CDF_CODE_PK NOT IN ('61', '62'))
-- Jointure entre la forme de sp?cialit? et la sac
JOIN SPFO_SPECIALITE_FORME SPFO1 ON (SPFO1.SPFO_SP_CODE_FK_PK = SP1.SP_CODE_SQ_PK
  AND SPFO1.SPFO_NUMORD ='1'
  )
JOIN CDF_CODIF CDFFO1 ON (CDFFO1.CDF_CODE_PK = SPFO1.SPFO_CDF_FO_CODE_FK_PK
  AND CDFFO1.CDF_NUMERO_PK = '06')
-- Jointure entre le dosage et la sp?cialit? (interaction)
JOIN FITVD1_INTERACTION_VOIE_DOSE FITVD1 ON FITVD1.FITVD1_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
LEFT JOIN CDF_CODIF CDFDO1 ON CDFDO1.CDF_CODE_PK = FITVD1.FITVD1_CDF_PP_CODE1_FK

JOIN IT2SP_TERME2SPECIALITE IT2SP ON (IT2SP.IT2SP_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
  AND IT1SP.IT1SP_FIT_CODE_FK_PK = IT2SP.IT2SP_FIT_CODE_FK_PK)
  
JOIN SP_SPECIALITE SP2 ON SP2.SP_CODE_SQ_PK = IT2SP.IT2SP_SP_CODE_FK_PK
JOIN GSP_GENERIQUE GSP2 ON GSP2.GSP_GSP_CODE_FK = SP2.SP_GSP_CODE_FK
JOIN PRODUIT_DC DC2 ON DC2.ID = GSP2.GSP_PRODUIT_DC_CODE_FK

-- Jointure entre la voie de sp?cialit? et la sac
JOIN SPVO_SPECIALITE_VOIE SPVO2 ON SPVO2.SPVO_SP_CODE_FK_PK = SP2.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFVO2 ON (CDFVO2.CDF_CODE_PK = SPVO2.SPVO_CDF_VO_CODE_FK_PK
  AND CDFVO2.CDF_NUMERO_PK = '18'
  AND CDFVO2.CDF_CODE_PK NOT IN ('61', '62'))
-- Jointure entre la forme de sp?cialit? et la sac
JOIN SPFO_SPECIALITE_FORME SPFO2 ON (SPFO2.SPFO_SP_CODE_FK_PK = SP2.SP_CODE_SQ_PK
  AND SPFO2.SPFO_NUMORD ='1'
  )
JOIN CDF_CODIF CDFFO2 ON (CDFFO2.CDF_CODE_PK = SPFO2.SPFO_CDF_FO_CODE_FK_PK
  AND CDFFO2.CDF_NUMERO_PK = '06')
-- Jointure entre le dosage et la sp?cialit? (interaction)
JOIN FITVD2_INTERACTION_VOIE_DOSE FITVD2 ON FITVD2.FITVD2_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
LEFT JOIN CDF_CODIF CDFDO2 ON CDFDO2.CDF_CODE_PK = FITVD2.FITVD2_CDF_PP_CODE2_FK

JOIN FITNA_INTERACTION_NATURE FITNA ON (FITNA.FITNA_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
  AND FITNA.FITNA_CDF_NAIT_CODE_FK_PK IN ('1', '2', '3', '4'))
;

-- Fichier numero 29 Produits DC ? Interactions SAC (TRAK.DrugDBUpload.PHCDrugInter.txt)

SELECT DISTINCT 'I^INGR' || replace(to_char(IT1SAC.IT1SAC_SAC_CODE_FK_PK, '00000'), ' ', '') ||
    '^INGR' || replace(to_char(IT2SAC.IT2SAC_SAC_CODE_FK_PK, '00000'), ' ', '') || 
    '^DRGINTS' || replace(to_char(FIT.FIT_CODE_SQ_PK, '00000'), ' ', '') ||
    '^MGR' || replace(to_char(CDF1.CDF_CODE_PK, '00000'), ' ', '')
FROM FIT_FICHEINTERAC FIT
JOIN IT1SAC_TERME1SUBACTIVE IT1SAC ON IT1SAC.IT1SAC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN IT2SAC_TERME2SUBACTIVE IT2SAC ON IT2SAC.IT2SAC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
JOIN FITNA_INTERACTION_NATURE FITNA ON FITNA.FITNA_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
--JOIN CDF FITNA
JOIN CDF_CODIF CDF1 ON CDF1.CDF_CODE_PK = FITNA.FITNA_CDF_NAIT_CODE_FK_PK
WHERE IT1SAC.IT1SAC_FIT_CODE_FK_PK = IT2SAC.IT2SAC_FIT_CODE_FK_PK
AND CDF1.CDF_NUMERO_PK = 'IY'
AND CDF1.CDF_NOM NOT LIKE 'zz%'
AND CDF1.CDF_NOM NOT LIKE 'NON RENSEIGNE';

-- Fichier numero 30 Produits DC ? Interactions simplifi?es (TRAK.DrugDBUpload.PHCGenericInter.txt)

SELECT * FROM FIT_FICHEINTERAC FIT;
SELECT * FROM IT1SAC_TERME1SUBACTIVE WHERE IT1SAC_FIT_CODE_FK_PK = '37';
SELECT * FROM SAC_SUBACTIVE WHERE SAC_CODE_SQ_PK = '1214';
SELECT * FROM IT2SAC_TERME2SUBACTIVE WHERE IT2SAC_FIT_CODE_FK_PK = '37';
SELECT * FROM SAC_SUBACTIVE WHERE SAC_CODE_SQ_PK IN ('1732', '1963', '440');

SELECT DISTINCT 'I^PHCGE' || replace(to_char(GSP1.GSP_PRODUIT_DC_CODE_FK, '00000'), ' ', '') ||
    '^PHCGE' || replace(to_char(GSP2.GSP_PRODUIT_DC_CODE_FK, '00000'), ' ', '') || 
    '^DRGINTS' || replace(to_char(SAC.FICHE, '00000'), ' ', '') ||
    '^MGR' || replace(to_char(SAC.NIV, '00000'), ' ', '')
FROM (
  SELECT IT1SAC.IT1SAC_SAC_CODE_FK_PK AS IT1, IT2SAC.IT2SAC_SAC_CODE_FK_PK AS IT2,FIT.FIT_CODE_SQ_PK AS FICHE , FITNA.FITNA_CDF_NAIT_CODE_FK_PK AS NIV
  FROM FIT_FICHEINTERAC FIT
  JOIN IT1SAC_TERME1SUBACTIVE IT1SAC ON IT1SAC.IT1SAC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
  JOIN IT2SAC_TERME2SUBACTIVE IT2SAC ON (IT2SAC.IT2SAC_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
    AND IT2SAC.IT2SAC_FIT_CODE_FK_PK = IT1SAC.IT1SAC_FIT_CODE_FK_PK)
  JOIN FITNA_INTERACTION_NATURE FITNA ON (FITNA.FITNA_FIT_CODE_FK_PK = FIT.FIT_CODE_SQ_PK
    AND FITNA.FITNA_CDF_NAIT_CODE_FK_PK IN ('1', '2', '3', '4'))
  --WHERE FIT.FIT_CODE_SQ_PK = '37'
  ) SAC
  
JOIN COSAC_COMPO_SUBACT COSAC1 ON COSAC1.COSAC_SAC_CODE_FK_PK = SAC.IT1
JOIN COSAC_COMPO_SUBACT COSAC2 ON COSAC2.COSAC_SAC_CODE_FK_PK = SAC.IT2

JOIN SP_SPECIALITE SP1 ON SP1.SP_CODE_SQ_PK = COSAC1.COSAC_SP_CODE_FK_PK
JOIN SP_SPECIALITE SP2 ON SP2.SP_CODE_SQ_PK = COSAC2.COSAC_SP_CODE_FK_PK

JOIN GSP_GENERIQUE GSP1 ON GSP1.GSP_GSP_CODE_FK = SP1.SP_GSP_CODE_FK
JOIN GSP_GENERIQUE GSP2 ON GSP2.GSP_GSP_CODE_FK = SP2.SP_GSP_CODE_FK
;

-- Fichier numero 31 Produits DC ? Substances, Forme, Voie, Dosage (TRAK.DrugDBUpload.PHCGenericRtFormsIngr.txt)

SELECT DISTINCT 
  replace('I^PHCGE' || to_char(DC.ID, '00000'), ' ', '') || 
  '^' || replace('PHCrt' || to_char(CDFVO.CDF_CODE_PK, '00000'), ' ', '') ||
  '^' || replace('PHCfr' || to_char(CDFFO.CDF_CODE_PK, '00000'), ' ', '') ||
  '^' || replace('INGR' || to_char(GSAC.GSAC_CODE_SQ_PK, '00000'), ' ', '') ||
  '^' || CONVERT(DOSAGE.COSAC_DOSAGE, 'US7ASCII', 'UTF8') || LOWER(DOSAGE.COSAC_UNITEDOSAGE)
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_SP_DC_CODE_FK
JOIN COSAC_COMPO_SUBACT COMPO ON COMPO.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN SAC_SUBACTIVE SAC ON SAC.SAC_CODE_SQ_PK = COMPO.COSAC_SAC_CODE_FK_PK
JOIN GSAC_PERE_SUBACT GSAC ON GSAC.GSAC_CODE_SQ_PK = SAC.SAC_GSAC_CODE_FK
-- Jointure pour la voie
JOIN SPVO_SPECIALITE_VOIE SPVO ON SPVO.SPVO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFVO ON (CDFVO.CDF_CODE_PK = SPVO.SPVO_CDF_VO_CODE_FK_PK
  AND CDFVO.CDF_NUMERO_PK = '18'
  AND CDFVO.CDF_NOM NOT LIKE 'zz%'
  AND CDFVO.CDF_NOM NOT LIKE 'ZZ%')
-- Jointure pour la forme
JOIN SPFO_SPECIALITE_FORME SPFO ON SPFO.SPFO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFFO ON (CDFFO.CDF_CODE_PK = SPFO.SPFO_CDF_FO_CODE_FK_PK
  AND CDFFO.CDF_NUMERO_PK = '06'
  AND CDFFO.CDF_NOM NOT LIKE 'zz%zz'
  AND CDFFO.CDF_NOM NOT LIKE 'NON RENSEIGNEE')
-- Jointure pour le dosage
JOIN COSAC_COMPO_SUBACT DOSAGE ON (DOSAGE.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSIGNE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEINGE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNEE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEINGNEE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NR')
;

-- Fichier numero 32 Produits DC ? Classes d??quivalence, Forme, Voie, Dosage (TRAK.DrugDBUpload.PHCGenericRtFormsTherCat.txt)

SELECT DISTINCT 
  replace('I^PHCGE' || to_char(DC.ID, '00000'), ' ', '') || 
  '^' || replace('PHCrt' || to_char(CDFVO.CDF_CODE_PK, '00000'), ' ', '') ||
  '^' || replace('PHCfr' || to_char(CDFFO.CDF_CODE_PK, '00000'), ' ', '') ||
  '^' || CONVERT(DOSAGE.COSAC_DOSAGE, 'US7ASCII', 'UTF8') || LOWER(DOSAGE.COSAC_UNITEDOSAGE) ||
  '^DTC' || CATC.CATC_CODE_PK
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_SP_DC_CODE_FK
-- Jointure pour la voie
JOIN SPVO_SPECIALITE_VOIE SPVO ON SPVO.SPVO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFVO ON (CDFVO.CDF_CODE_PK = SPVO.SPVO_CDF_VO_CODE_FK_PK
  AND CDFVO.CDF_NUMERO_PK = '18'
  AND CDFVO.CDF_NOM NOT LIKE 'zz%'
  AND CDFVO.CDF_NOM NOT LIKE 'ZZ%')
-- Jointure pour la forme
JOIN SPFO_SPECIALITE_FORME SPFO ON SPFO.SPFO_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN CDF_CODIF CDFFO ON (CDFFO.CDF_CODE_PK = SPFO.SPFO_CDF_FO_CODE_FK_PK
  AND CDFFO.CDF_NUMERO_PK = '06'
  AND CDFFO.CDF_NOM NOT LIKE 'zz%zz'
  AND CDFFO.CDF_NOM NOT LIKE 'NON RENSEIGNEE')
-- Jointure pour le dosage
JOIN COSAC_COMPO_SUBACT DOSAGE ON (DOSAGE.COSAC_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSIGNE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEINGE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEIGNEE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NON RENSEINGNEE'
  AND DOSAGE.COSAC_DOSAGE NOT LIKE 'NR')
-- Jointure pour classe ATC
JOIN CATC_CLASSEATC CATC ON CATC.CATC_CODE_PK = SP.SP_CATC_CODE_FK
;

-- Fichier numero 33 Produits DC - Grossesse (TRAK.DrugDBUpload.PHCGenPregCat.txt)

SELECT DISTINCT
  replace('I^PHCGE' || to_char(DC.ID, '00000'), ' ', '') || 
  '^' || replace('PREGCAT' || to_char(SUBSTR(CDFGR.CDF_CODE_PK,2,3), '00000'), ' ', '')
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_SP_DC_CODE_FK
JOIN FGASP_GRALSPE GRSP ON GRSP.FGASP_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN FGARIG_RISQUE_GROSSESSE GR ON GR.FGARIG_FGA_CODE_FK_PK = GRSP.FGASP_FGA_CODE_FK_PK
JOIN CDF_CODIF CDFGR ON (CDFGR.CDF_CODE_PK = GR.FGARIG_CDF_RI_CODE_FK
  AND CDFGR.CDF_NUMERO_PK = 'GR'
  AND CDFGR.CDF_CODE_PK LIKE 'R%'
  AND CDFGR.CDF_CODE_PK NOT IN ('R10', 'R13', 'R6', 'R7', 'R25', 'R20', 'R15', 'R11', 'R14', 'R9', 'R2','R', 'R26'))
;

-- Fichier numero 34 Produits DC ? Contre-Indications (TRAK.DrugDBUpload.PHCGenericContraIndication.txt)

SELECT * FROM SP_SPECIALITE;
SELECT * FROM PRE_PRESENTATION;
SELECT * FROM SPLAB_SPECIALITE_LABO;
SELECT * FROM SPLABEX_SPE_LABO_EXPLOITANT;

-- Fichier numero 35 Sp?cialit?s (TRAK.DrugDBUpload.PHCDrgMaster.txt)

SELECT DISTINCT 
  replace('' || to_char(DC.ID, '00000'), ' ', '') ||
  '^' || SP.SP_CODE_SQ_PK ||
  '^' || SP_NOM ||
  '^' || CATC3.CATC_CATC_CODE_FK ||
  '^' || SP.SP_NOMLONG ||
  '^' || SP.SP_CIPUCD ||
  '^' || SP.SP_CDF_LI_CODE_FK ||
  '^' || CATC3.CATC_CODE_PK ||
  '^' || EXPLOITANT.SPLABEX_CDF_LAB_CODE_FK_PK ||
  '^' || TITULAIRE.SPLAB_CDF_LAB_CODE_FK_PK
FROM PRODUIT_DC DC
JOIN GSP_GENERIQUE GSP ON GSP.GSP_PRODUIT_DC_CODE_FK = DC.ID
JOIN SP_SPECIALITE SP ON SP.SP_GSP_CODE_FK = GSP.GSP_SP_DC_CODE_FK
JOIN CATC_CLASSEATC CATC3 ON (CATC3.CATC_CODE_PK = SP.SP_CATC_CODE_FK
  AND LENGTH(CATC3.CATC_CODE_PK) = 5)
JOIN SPLAB_SPECIALITE_LABO TITULAIRE ON TITULAIRE.SPLAB_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
JOIN SPLABEX_SPE_LABO_EXPLOITANT EXPLOITANT ON EXPLOITANT.SPLABEX_SP_CODE_FK_PK = SP.SP_CODE_SQ_PK
;